// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/flutter_recorder.h`.
///
/// Regenerate bindings with
/// `dart run ffigen --config ffigen.yaml`
/// or
/// `export CPATH="$(clang -v 2>&1 | grep "Selected GCC installation" | rev | cut -d' ' -f1 | rev)/include";  dart run ffigen --config ffigen.yaml`
///
class FlutterRecorderBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  FlutterRecorderBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  FlutterRecorderBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void flutter_recorder_createWorkerInWasm() {
    return _flutter_recorder_createWorkerInWasm();
  }

  late final _flutter_recorder_createWorkerInWasmPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
          'flutter_recorder_createWorkerInWasm');
  late final _flutter_recorder_createWorkerInWasm =
      _flutter_recorder_createWorkerInWasmPtr.asFunction<void Function()>();

  void flutter_recorder_setDartEventCallback(
    dartSilenceChangedCallback_t silence_changed_callback,
    dartStreamDataCallback_t stream_data_callback,
  ) {
    return _flutter_recorder_setDartEventCallback(
      silence_changed_callback,
      stream_data_callback,
    );
  }

  late final _flutter_recorder_setDartEventCallbackPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  dartSilenceChangedCallback_t, dartStreamDataCallback_t)>>(
      'flutter_recorder_setDartEventCallback');
  late final _flutter_recorder_setDartEventCallback =
      _flutter_recorder_setDartEventCallbackPtr.asFunction<
          void Function(
              dartSilenceChangedCallback_t, dartStreamDataCallback_t)>();

  void flutter_recorder_nativeFree(
    ffi.Pointer<ffi.Void> pointer,
  ) {
    return _flutter_recorder_nativeFree(
      pointer,
    );
  }

  late final _flutter_recorder_nativeFreePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'flutter_recorder_nativeFree');
  late final _flutter_recorder_nativeFree = _flutter_recorder_nativeFreePtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void flutter_recorder_listCaptureDevices(
    ffi.Pointer<ffi.Pointer<ffi.Char>> devicesName,
    ffi.Pointer<ffi.Pointer<ffi.Int>> deviceId,
    ffi.Pointer<ffi.Pointer<ffi.Int>> isDefault,
    ffi.Pointer<ffi.Int> n_devices,
  ) {
    return _flutter_recorder_listCaptureDevices(
      devicesName,
      deviceId,
      isDefault,
      n_devices,
    );
  }

  late final _flutter_recorder_listCaptureDevicesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
              ffi.Pointer<ffi.Pointer<ffi.Int>>,
              ffi.Pointer<ffi.Pointer<ffi.Int>>,
              ffi.Pointer<ffi.Int>)>>('flutter_recorder_listCaptureDevices');
  late final _flutter_recorder_listCaptureDevices =
      _flutter_recorder_listCaptureDevicesPtr.asFunction<
          void Function(
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
              ffi.Pointer<ffi.Pointer<ffi.Int>>,
              ffi.Pointer<ffi.Pointer<ffi.Int>>,
              ffi.Pointer<ffi.Int>)>();

  void flutter_recorder_freeListCaptureDevices(
    ffi.Pointer<ffi.Pointer<ffi.Char>> devicesName,
    ffi.Pointer<ffi.Pointer<ffi.Int>> deviceId,
    ffi.Pointer<ffi.Pointer<ffi.Int>> isDefault,
    int n_devices,
  ) {
    return _flutter_recorder_freeListCaptureDevices(
      devicesName,
      deviceId,
      isDefault,
      n_devices,
    );
  }

  late final _flutter_recorder_freeListCaptureDevicesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
              ffi.Pointer<ffi.Pointer<ffi.Int>>,
              ffi.Pointer<ffi.Pointer<ffi.Int>>,
              ffi.Int)>>('flutter_recorder_freeListCaptureDevices');
  late final _flutter_recorder_freeListCaptureDevices =
      _flutter_recorder_freeListCaptureDevicesPtr.asFunction<
          void Function(
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
              ffi.Pointer<ffi.Pointer<ffi.Int>>,
              ffi.Pointer<ffi.Pointer<ffi.Int>>,
              int)>();

  CaptureErrors flutter_recorder_init(
    int deviceID,
    int pcmFormat,
    int sampleRate,
    int channels,
    int captureOnly,
  ) {
    return CaptureErrors.fromValue(_flutter_recorder_init(
      deviceID,
      pcmFormat,
      sampleRate,
      channels,
      captureOnly,
    ));
  }

  late final _flutter_recorder_initPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Int, ffi.Int, ffi.UnsignedInt,
              ffi.UnsignedInt, ffi.Int)>>('flutter_recorder_init');
  late final _flutter_recorder_init = _flutter_recorder_initPtr
      .asFunction<int Function(int, int, int, int, int)>();

  void flutter_recorder_deinit() {
    return _flutter_recorder_deinit();
  }

  late final _flutter_recorder_deinitPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
          'flutter_recorder_deinit');
  late final _flutter_recorder_deinit =
      _flutter_recorder_deinitPtr.asFunction<void Function()>();

  int flutter_recorder_isInited() {
    return _flutter_recorder_isInited();
  }

  late final _flutter_recorder_isInitedPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>(
          'flutter_recorder_isInited');
  late final _flutter_recorder_isInited =
      _flutter_recorder_isInitedPtr.asFunction<int Function()>();

  int flutter_recorder_isDeviceStarted() {
    return _flutter_recorder_isDeviceStarted();
  }

  late final _flutter_recorder_isDeviceStartedPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>(
          'flutter_recorder_isDeviceStarted');
  late final _flutter_recorder_isDeviceStarted =
      _flutter_recorder_isDeviceStartedPtr.asFunction<int Function()>();

  CaptureErrors flutter_recorder_start() {
    return CaptureErrors.fromValue(_flutter_recorder_start());
  }

  late final _flutter_recorder_startPtr =
      _lookup<ffi.NativeFunction<ffi.UnsignedInt Function()>>(
          'flutter_recorder_start');
  late final _flutter_recorder_start =
      _flutter_recorder_startPtr.asFunction<int Function()>();

  void flutter_recorder_stop() {
    return _flutter_recorder_stop();
  }

  late final _flutter_recorder_stopPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('flutter_recorder_stop');
  late final _flutter_recorder_stop =
      _flutter_recorder_stopPtr.asFunction<void Function()>();

  void flutter_recorder_startStreamingData() {
    return _flutter_recorder_startStreamingData();
  }

  late final _flutter_recorder_startStreamingDataPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
          'flutter_recorder_startStreamingData');
  late final _flutter_recorder_startStreamingData =
      _flutter_recorder_startStreamingDataPtr.asFunction<void Function()>();

  void flutter_recorder_stopStreamingData() {
    return _flutter_recorder_stopStreamingData();
  }

  late final _flutter_recorder_stopStreamingDataPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
          'flutter_recorder_stopStreamingData');
  late final _flutter_recorder_stopStreamingData =
      _flutter_recorder_stopStreamingDataPtr.asFunction<void Function()>();

  void flutter_recorder_setSilenceDetection(
    bool enable,
  ) {
    return _flutter_recorder_setSilenceDetection(
      enable,
    );
  }

  late final _flutter_recorder_setSilenceDetectionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
          'flutter_recorder_setSilenceDetection');
  late final _flutter_recorder_setSilenceDetection =
      _flutter_recorder_setSilenceDetectionPtr
          .asFunction<void Function(bool)>();

  void flutter_recorder_setSilenceThresholdDb(
    double silenceThresholdDb,
  ) {
    return _flutter_recorder_setSilenceThresholdDb(
      silenceThresholdDb,
    );
  }

  late final _flutter_recorder_setSilenceThresholdDbPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
          'flutter_recorder_setSilenceThresholdDb');
  late final _flutter_recorder_setSilenceThresholdDb =
      _flutter_recorder_setSilenceThresholdDbPtr
          .asFunction<void Function(double)>();

  void flutter_recorder_setSilenceDuration(
    double silenceDuration,
  ) {
    return _flutter_recorder_setSilenceDuration(
      silenceDuration,
    );
  }

  late final _flutter_recorder_setSilenceDurationPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
          'flutter_recorder_setSilenceDuration');
  late final _flutter_recorder_setSilenceDuration =
      _flutter_recorder_setSilenceDurationPtr
          .asFunction<void Function(double)>();

  void flutter_recorder_setSecondsOfAudioToWriteBefore(
    double secondsOfAudioToWriteBefore,
  ) {
    return _flutter_recorder_setSecondsOfAudioToWriteBefore(
      secondsOfAudioToWriteBefore,
    );
  }

  late final _flutter_recorder_setSecondsOfAudioToWriteBeforePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
          'flutter_recorder_setSecondsOfAudioToWriteBefore');
  late final _flutter_recorder_setSecondsOfAudioToWriteBefore =
      _flutter_recorder_setSecondsOfAudioToWriteBeforePtr
          .asFunction<void Function(double)>();

  CaptureErrors flutter_recorder_startRecording(
    ffi.Pointer<ffi.Char> path,
  ) {
    return CaptureErrors.fromValue(_flutter_recorder_startRecording(
      path,
    ));
  }

  late final _flutter_recorder_startRecordingPtr = _lookup<
          ffi.NativeFunction<ffi.UnsignedInt Function(ffi.Pointer<ffi.Char>)>>(
      'flutter_recorder_startRecording');
  late final _flutter_recorder_startRecording =
      _flutter_recorder_startRecordingPtr
          .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  void flutter_recorder_setPauseRecording(
    bool pause,
  ) {
    return _flutter_recorder_setPauseRecording(
      pause,
    );
  }

  late final _flutter_recorder_setPauseRecordingPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
          'flutter_recorder_setPauseRecording');
  late final _flutter_recorder_setPauseRecording =
      _flutter_recorder_setPauseRecordingPtr.asFunction<void Function(bool)>();

  void flutter_recorder_stopRecording() {
    return _flutter_recorder_stopRecording();
  }

  late final _flutter_recorder_stopRecordingPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
          'flutter_recorder_stopRecording');
  late final _flutter_recorder_stopRecording =
      _flutter_recorder_stopRecordingPtr.asFunction<void Function()>();

  void flutter_recorder_getVolumeDb(
    ffi.Pointer<ffi.Float> volumeDb,
  ) {
    return _flutter_recorder_getVolumeDb(
      volumeDb,
    );
  }

  late final _flutter_recorder_getVolumeDbPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Float>)>>(
          'flutter_recorder_getVolumeDb');
  late final _flutter_recorder_getVolumeDb = _flutter_recorder_getVolumeDbPtr
      .asFunction<void Function(ffi.Pointer<ffi.Float>)>();

  void flutter_recorder_getFft(
    ffi.Pointer<ffi.Pointer<ffi.Float>> fft,
    ffi.Pointer<ffi.Bool> isTheSameAsBefore,
  ) {
    return _flutter_recorder_getFft(
      fft,
      isTheSameAsBefore,
    );
  }

  late final _flutter_recorder_getFftPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Pointer<ffi.Float>>,
              ffi.Pointer<ffi.Bool>)>>('flutter_recorder_getFft');
  late final _flutter_recorder_getFft = _flutter_recorder_getFftPtr.asFunction<
      void Function(
          ffi.Pointer<ffi.Pointer<ffi.Float>>, ffi.Pointer<ffi.Bool>)>();

  void flutter_recorder_getWave(
    ffi.Pointer<ffi.Pointer<ffi.Float>> wave,
    ffi.Pointer<ffi.Bool> isTheSameAsBefore,
  ) {
    return _flutter_recorder_getWave(
      wave,
      isTheSameAsBefore,
    );
  }

  late final _flutter_recorder_getWavePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Pointer<ffi.Float>>,
              ffi.Pointer<ffi.Bool>)>>('flutter_recorder_getWave');
  late final _flutter_recorder_getWave =
      _flutter_recorder_getWavePtr.asFunction<
          void Function(
              ffi.Pointer<ffi.Pointer<ffi.Float>>, ffi.Pointer<ffi.Bool>)>();

  void flutter_recorder_getTexture(
    ffi.Pointer<ffi.Pointer<ffi.Float>> samples,
    ffi.Pointer<ffi.Bool> isTheSameAsBefore,
  ) {
    return _flutter_recorder_getTexture(
      samples,
      isTheSameAsBefore,
    );
  }

  late final _flutter_recorder_getTexturePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Pointer<ffi.Float>>,
              ffi.Pointer<ffi.Bool>)>>('flutter_recorder_getTexture');
  late final _flutter_recorder_getTexture =
      _flutter_recorder_getTexturePtr.asFunction<
          void Function(
              ffi.Pointer<ffi.Pointer<ffi.Float>>, ffi.Pointer<ffi.Bool>)>();

  void flutter_recorder_getTexture2D(
    ffi.Pointer<ffi.Pointer<ffi.Float>> samples,
    ffi.Pointer<ffi.Bool> isTheSameAsBefore,
  ) {
    return _flutter_recorder_getTexture2D(
      samples,
      isTheSameAsBefore,
    );
  }

  late final _flutter_recorder_getTexture2DPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Pointer<ffi.Float>>,
              ffi.Pointer<ffi.Bool>)>>('flutter_recorder_getTexture2D');
  late final _flutter_recorder_getTexture2D =
      _flutter_recorder_getTexture2DPtr.asFunction<
          void Function(
              ffi.Pointer<ffi.Pointer<ffi.Float>>, ffi.Pointer<ffi.Bool>)>();

  double flutter_recorder_getTextureValue(
    int row,
    int column,
  ) {
    return _flutter_recorder_getTextureValue(
      row,
      column,
    );
  }

  late final _flutter_recorder_getTextureValuePtr =
      _lookup<ffi.NativeFunction<ffi.Float Function(ffi.Int, ffi.Int)>>(
          'flutter_recorder_getTextureValue');
  late final _flutter_recorder_getTextureValue =
      _flutter_recorder_getTextureValuePtr
          .asFunction<double Function(int, int)>();

  void flutter_recorder_setFftSmoothing(
    double smooth,
  ) {
    return _flutter_recorder_setFftSmoothing(
      smooth,
    );
  }

  late final _flutter_recorder_setFftSmoothingPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
          'flutter_recorder_setFftSmoothing');
  late final _flutter_recorder_setFftSmoothing =
      _flutter_recorder_setFftSmoothingPtr.asFunction<void Function(double)>();



  /// //////////////////////
  /// GETTERS
  /// //////////////////////

  int flutter_recorder_getSampleRate() {
    return _flutter_recorder_getSampleRate();
  }

  late final _flutter_recorder_getSampleRatePtr =
      _lookup<ffi.NativeFunction<ffi.UnsignedInt Function()>>(
          'flutter_recorder_getSampleRate');
  late final _flutter_recorder_getSampleRate =
      _flutter_recorder_getSampleRatePtr.asFunction<int Function()>();

  int flutter_recorder_getCaptureChannels() {
    return _flutter_recorder_getCaptureChannels();
  }

  late final _flutter_recorder_getCaptureChannelsPtr =
      _lookup<ffi.NativeFunction<ffi.UnsignedInt Function()>>(
          'flutter_recorder_getCaptureChannels');
  late final _flutter_recorder_getCaptureChannels =
      _flutter_recorder_getCaptureChannelsPtr.asFunction<int Function()>();

  int flutter_recorder_getPlaybackChannels() {
    return _flutter_recorder_getPlaybackChannels();
  }

  late final _flutter_recorder_getPlaybackChannelsPtr =
      _lookup<ffi.NativeFunction<ffi.UnsignedInt Function()>>(
          'flutter_recorder_getPlaybackChannels');
  late final _flutter_recorder_getPlaybackChannels =
      _flutter_recorder_getPlaybackChannelsPtr.asFunction<int Function()>();

  int flutter_recorder_getCaptureFormat() {
    return _flutter_recorder_getCaptureFormat();
  }

  late final _flutter_recorder_getCaptureFormatPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>(
          'flutter_recorder_getCaptureFormat');
  late final _flutter_recorder_getCaptureFormat =
      _flutter_recorder_getCaptureFormatPtr.asFunction<int Function()>();

  int flutter_recorder_getPlaybackFormat() {
    return _flutter_recorder_getPlaybackFormat();
  }

  late final _flutter_recorder_getPlaybackFormatPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>(
          'flutter_recorder_getPlaybackFormat');
  late final _flutter_recorder_getPlaybackFormat =
      _flutter_recorder_getPlaybackFormatPtr.asFunction<int Function()>();
  void flutter_recorder_setMonitoring(
    bool enabled,
  ) {
    return _flutter_recorder_setMonitoring(
      enabled,
    );
  }

  late final _flutter_recorder_setMonitoringPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
          'flutter_recorder_setMonitoring');
  late final _flutter_recorder_setMonitoring =
      _flutter_recorder_setMonitoringPtr.asFunction<void Function(bool)>();

  void flutter_recorder_setMonitoringMode(
    int mode,
  ) {
    return _flutter_recorder_setMonitoringMode(
      mode,
    );
  }

  late final _flutter_recorder_setMonitoringModePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>(
          'flutter_recorder_setMonitoringMode');
  late final _flutter_recorder_setMonitoringMode =
      _flutter_recorder_setMonitoringModePtr.asFunction<void Function(int)>();

  /// //////////////////////
  /// SLAVE MODE
  /// //////////////////////
  /// Check if slave audio is ready (first callback has run successfully)
  /// Used to wait for the audio pipeline to stabilize before calibration
  int flutter_recorder_isSlaveAudioReady() {
    return _flutter_recorder_isSlaveAudioReady();
  }

  late final _flutter_recorder_isSlaveAudioReadyPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>(
          'flutter_recorder_isSlaveAudioReady');
  late final _flutter_recorder_isSlaveAudioReady =
      _flutter_recorder_isSlaveAudioReadyPtr.asFunction<int Function()>();

  /// //////////////////////
  /// FILTERS
  /// //////////////////////
  int flutter_recorder_isFilterActive(
    RecorderFilterType filterType,
  ) {
    return _flutter_recorder_isFilterActive(
      filterType.value,
    );
  }

  late final _flutter_recorder_isFilterActivePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.UnsignedInt)>>(
          'flutter_recorder_isFilterActive');
  late final _flutter_recorder_isFilterActive =
      _flutter_recorder_isFilterActivePtr.asFunction<int Function(int)>();

  CaptureErrors flutter_recorder_addFilter(
    RecorderFilterType filterType,
  ) {
    return CaptureErrors.fromValue(_flutter_recorder_addFilter(
      filterType.value,
    ));
  }

  late final _flutter_recorder_addFilterPtr =
      _lookup<ffi.NativeFunction<ffi.UnsignedInt Function(ffi.UnsignedInt)>>(
          'flutter_recorder_addFilter');
  late final _flutter_recorder_addFilter =
      _flutter_recorder_addFilterPtr.asFunction<int Function(int)>();

  CaptureErrors flutter_recorder_removeFilter(
    RecorderFilterType filterType,
  ) {
    return CaptureErrors.fromValue(_flutter_recorder_removeFilter(
      filterType.value,
    ));
  }

  late final _flutter_recorder_removeFilterPtr =
      _lookup<ffi.NativeFunction<ffi.UnsignedInt Function(ffi.UnsignedInt)>>(
          'flutter_recorder_removeFilter');
  late final _flutter_recorder_removeFilter =
      _flutter_recorder_removeFilterPtr.asFunction<int Function(int)>();

  void flutter_recorder_getFilterParamNames(
    RecorderFilterType filterType,
    ffi.Pointer<ffi.Pointer<ffi.Char>> names,
    ffi.Pointer<ffi.Int> paramsCount,
  ) {
    return _flutter_recorder_getFilterParamNames(
      filterType.value,
      names,
      paramsCount,
    );
  }

  late final _flutter_recorder_getFilterParamNamesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.UnsignedInt, ffi.Pointer<ffi.Pointer<ffi.Char>>,
              ffi.Pointer<ffi.Int>)>>('flutter_recorder_getFilterParamNames');
  late final _flutter_recorder_getFilterParamNames =
      _flutter_recorder_getFilterParamNamesPtr.asFunction<
          void Function(
              int, ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Pointer<ffi.Int>)>();

  void flutter_recorder_setFilterParams(
    RecorderFilterType filterType,
    int attributeId,
    double value,
  ) {
    return _flutter_recorder_setFilterParams(
      filterType.value,
      attributeId,
      value,
    );
  }

  late final _flutter_recorder_setFilterParamsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.UnsignedInt, ffi.Int,
              ffi.Float)>>('flutter_recorder_setFilterParams');
  late final _flutter_recorder_setFilterParams =
      _flutter_recorder_setFilterParamsPtr
          .asFunction<void Function(int, int, double)>();

  double flutter_recorder_getFilterParams(
    RecorderFilterType filterType,
    int attributeId,
  ) {
    return _flutter_recorder_getFilterParams(
      filterType.value,
      attributeId,
    );
  }

  late final _flutter_recorder_getFilterParamsPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function(ffi.UnsignedInt, ffi.Int)>>(
          'flutter_recorder_getFilterParams');
  late final _flutter_recorder_getFilterParams =
      _flutter_recorder_getFilterParamsPtr
          .asFunction<double Function(int, int)>();

  /// //////////////////////
  /// AEC (Acoustic Echo Cancellation)
  /// //////////////////////
  ffi.Pointer<ffi.Void> flutter_recorder_aec_createReferenceBuffer(
    int sampleRate,
    int channels,
  ) {
    return _flutter_recorder_aec_createReferenceBuffer(
      sampleRate,
      channels,
    );
  }

  late final _flutter_recorder_aec_createReferenceBufferPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(ffi.UnsignedInt,
              ffi.UnsignedInt)>>('flutter_recorder_aec_createReferenceBuffer');
  late final _flutter_recorder_aec_createReferenceBuffer =
      _flutter_recorder_aec_createReferenceBufferPtr
          .asFunction<ffi.Pointer<ffi.Void> Function(int, int)>();

  void flutter_recorder_aec_destroyReferenceBuffer() {
    return _flutter_recorder_aec_destroyReferenceBuffer();
  }

  late final _flutter_recorder_aec_destroyReferenceBufferPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
          'flutter_recorder_aec_destroyReferenceBuffer');
  late final _flutter_recorder_aec_destroyReferenceBuffer =
      _flutter_recorder_aec_destroyReferenceBufferPtr
          .asFunction<void Function()>();

  ffi.Pointer<ffi.Void> flutter_recorder_aec_getOutputCallback() {
    return _flutter_recorder_aec_getOutputCallback();
  }

  late final _flutter_recorder_aec_getOutputCallbackPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function()>>(
          'flutter_recorder_aec_getOutputCallback');
  late final _flutter_recorder_aec_getOutputCallback =
      _flutter_recorder_aec_getOutputCallbackPtr
          .asFunction<ffi.Pointer<ffi.Void> Function()>();

  void flutter_recorder_aec_resetBuffer() {
    return _flutter_recorder_aec_resetBuffer();
  }

  late final _flutter_recorder_aec_resetBufferPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
          'flutter_recorder_aec_resetBuffer');
  late final _flutter_recorder_aec_resetBuffer =
      _flutter_recorder_aec_resetBufferPtr.asFunction<void Function()>();

  /// AEC Mode Control (A/B Testing)
  void flutter_recorder_aec_setMode(
    int mode,
  ) {
    return _flutter_recorder_aec_setMode(
      mode,
    );
  }

  late final _flutter_recorder_aec_setModePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>(
          'flutter_recorder_aec_setMode');
  late final _flutter_recorder_aec_setMode =
      _flutter_recorder_aec_setModePtr.asFunction<void Function(int)>();

  int flutter_recorder_aec_getMode() {
    return _flutter_recorder_aec_getMode();
  }

  late final _flutter_recorder_aec_getModePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>(
          'flutter_recorder_aec_getMode');
  late final _flutter_recorder_aec_getMode =
      _flutter_recorder_aec_getModePtr.asFunction<int Function()>();

  /// //////////////////////
  /// Neural Model Control
  /// //////////////////////
  /// Load neural model by type
  /// modelType: 0=NONE, 1=AEC_MASK_V3
  /// assetBasePath: Platform-specific path to assets directory
  /// Returns: 1 if successful, 0 if failed
  int flutter_recorder_neural_loadModel(
    int modelType,
    ffi.Pointer<ffi.Char> assetBasePath,
  ) {
    return _flutter_recorder_neural_loadModel(
      modelType,
      assetBasePath,
    );
  }

  late final _flutter_recorder_neural_loadModelPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Pointer<ffi.Char>)>>(
      'flutter_recorder_neural_loadModel');
  late final _flutter_recorder_neural_loadModel =
      _flutter_recorder_neural_loadModelPtr
          .asFunction<int Function(int, ffi.Pointer<ffi.Char>)>();

  /// Get currently loaded neural model type
  /// Returns: 0=NONE, 1=AEC_MASK_V3
  int flutter_recorder_neural_getLoadedModel() {
    return _flutter_recorder_neural_getLoadedModel();
  }

  late final _flutter_recorder_neural_getLoadedModelPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>(
          'flutter_recorder_neural_getLoadedModel');
  late final _flutter_recorder_neural_getLoadedModel =
      _flutter_recorder_neural_getLoadedModelPtr.asFunction<int Function()>();

  /// Enable/disable neural post-filter
  void flutter_recorder_neural_setEnabled(
    int enabled,
  ) {
    return _flutter_recorder_neural_setEnabled(
      enabled,
    );
  }

  late final _flutter_recorder_neural_setEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>(
          'flutter_recorder_neural_setEnabled');
  late final _flutter_recorder_neural_setEnabled =
      _flutter_recorder_neural_setEnabledPtr.asFunction<void Function(int)>();

  /// Check if neural post-filter is enabled
  int flutter_recorder_neural_isEnabled() {
    return _flutter_recorder_neural_isEnabled();
  }

  late final _flutter_recorder_neural_isEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>(
          'flutter_recorder_neural_isEnabled');
  late final _flutter_recorder_neural_isEnabled =
      _flutter_recorder_neural_isEnabledPtr.asFunction<int Function()>();

  /// Calibration signal types
  /// 0 = Chirp (log sweep), 1 = Click (impulse train)
  ffi.Pointer<ffi.Uint8> flutter_recorder_aec_generateCalibrationSignal(
    int sampleRate,
    int channels,
    ffi.Pointer<ffi.Size> outSize,
    int signalType,
  ) {
    return _flutter_recorder_aec_generateCalibrationSignal(
      sampleRate,
      channels,
      outSize,
      signalType,
    );
  }

  late final _flutter_recorder_aec_generateCalibrationSignalPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Uint8> Function(
              ffi.UnsignedInt,
              ffi.UnsignedInt,
              ffi.Pointer<ffi.Size>,
              ffi.Int)>>('flutter_recorder_aec_generateCalibrationSignal');
  late final _flutter_recorder_aec_generateCalibrationSignal =
      _flutter_recorder_aec_generateCalibrationSignalPtr.asFunction<
          ffi.Pointer<ffi.Uint8> Function(
              int, int, ffi.Pointer<ffi.Size>, int)>();

  void flutter_recorder_aec_startCalibrationCapture(
    int maxSamples,
  ) {
    return _flutter_recorder_aec_startCalibrationCapture(
      maxSamples,
    );
  }

  late final _flutter_recorder_aec_startCalibrationCapturePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Size)>>(
          'flutter_recorder_aec_startCalibrationCapture');
  late final _flutter_recorder_aec_startCalibrationCapture =
      _flutter_recorder_aec_startCalibrationCapturePtr
          .asFunction<void Function(int)>();

  void flutter_recorder_aec_stopCalibrationCapture() {
    return _flutter_recorder_aec_stopCalibrationCapture();
  }

  late final _flutter_recorder_aec_stopCalibrationCapturePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
          'flutter_recorder_aec_stopCalibrationCapture');
  late final _flutter_recorder_aec_stopCalibrationCapture =
      _flutter_recorder_aec_stopCalibrationCapturePtr
          .asFunction<void Function()>();

  void flutter_recorder_aec_captureForAnalysis() {
    return _flutter_recorder_aec_captureForAnalysis();
  }

  late final _flutter_recorder_aec_captureForAnalysisPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
          'flutter_recorder_aec_captureForAnalysis');
  late final _flutter_recorder_aec_captureForAnalysis =
      _flutter_recorder_aec_captureForAnalysisPtr.asFunction<void Function()>();

  int flutter_recorder_aec_runCalibrationAnalysis(
    int sampleRate,
    ffi.Pointer<ffi.Float> outDelayMs,
    ffi.Pointer<ffi.Float> outEchoGain,
    ffi.Pointer<ffi.Float> outCorrelation,
  ) {
    return _flutter_recorder_aec_runCalibrationAnalysis(
      sampleRate,
      outDelayMs,
      outEchoGain,
      outCorrelation,
    );
  }

  late final _flutter_recorder_aec_runCalibrationAnalysisPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(ffi.UnsignedInt, ffi.Pointer<ffi.Float>,
                  ffi.Pointer<ffi.Float>, ffi.Pointer<ffi.Float>)>>(
      'flutter_recorder_aec_runCalibrationAnalysis');
  late final _flutter_recorder_aec_runCalibrationAnalysis =
      _flutter_recorder_aec_runCalibrationAnalysisPtr.asFunction<
          int Function(int, ffi.Pointer<ffi.Float>, ffi.Pointer<ffi.Float>,
              ffi.Pointer<ffi.Float>)>();

  void flutter_recorder_aec_resetCalibration() {
    return _flutter_recorder_aec_resetCalibration();
  }

  late final _flutter_recorder_aec_resetCalibrationPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
          'flutter_recorder_aec_resetCalibration');
  late final _flutter_recorder_aec_resetCalibration =
      _flutter_recorder_aec_resetCalibrationPtr.asFunction<void Function()>();

  void flutter_recorder_set_aec_stats_callback(
    AecStatsCallback callback,
  ) {
    return _flutter_recorder_set_aec_stats_callback(
      callback,
    );
  }

  late final _flutter_recorder_set_aec_stats_callbackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(AecStatsCallback)>>(
          'flutter_recorder_set_aec_stats_callback');
  late final _flutter_recorder_set_aec_stats_callback =
      _flutter_recorder_set_aec_stats_callbackPtr
          .asFunction<void Function(AecStatsCallback)>();

  int flutter_recorder_aec_runCalibrationWithImpulse(
    int sampleRate,
    ffi.Pointer<ffi.Float> outDelayMs,
    ffi.Pointer<ffi.Float> outEchoGain,
    ffi.Pointer<ffi.Float> outCorrelation,
    ffi.Pointer<ffi.Int> outImpulseLength,
    ffi.Pointer<ffi.Int64> outCalibratedOffset,
  ) {
    return _flutter_recorder_aec_runCalibrationWithImpulse(
      sampleRate,
      outDelayMs,
      outEchoGain,
      outCorrelation,
      outImpulseLength,
      outCalibratedOffset,
    );
  }

  late final _flutter_recorder_aec_runCalibrationWithImpulsePtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(
                  ffi.UnsignedInt,
                  ffi.Pointer<ffi.Float>,
                  ffi.Pointer<ffi.Float>,
                  ffi.Pointer<ffi.Float>,
                  ffi.Pointer<ffi.Int>,
                  ffi.Pointer<ffi.Int64>)>>(
      'flutter_recorder_aec_runCalibrationWithImpulse');
  late final _flutter_recorder_aec_runCalibrationWithImpulse =
      _flutter_recorder_aec_runCalibrationWithImpulsePtr.asFunction<
          int Function(
              int,
              ffi.Pointer<ffi.Float>,
              ffi.Pointer<ffi.Float>,
              ffi.Pointer<ffi.Float>,
              ffi.Pointer<ffi.Int>,
              ffi.Pointer<ffi.Int64>)>();

  /// Get stored impulse response from last calibration
  int flutter_recorder_aec_getImpulseResponse(
    ffi.Pointer<ffi.Float> dest,
    int maxLength,
  ) {
    return _flutter_recorder_aec_getImpulseResponse(
      dest,
      maxLength,
    );
  }

  late final _flutter_recorder_aec_getImpulseResponsePtr = _lookup<
          ffi
          .NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Float>, ffi.Int)>>(
      'flutter_recorder_aec_getImpulseResponse');
  late final _flutter_recorder_aec_getImpulseResponse =
      _flutter_recorder_aec_getImpulseResponsePtr
          .asFunction<int Function(ffi.Pointer<ffi.Float>, int)>();

  /// Apply stored impulse response to AEC filter
  void flutter_recorder_aec_applyImpulseResponse() {
    return _flutter_recorder_aec_applyImpulseResponse();
  }

  late final _flutter_recorder_aec_applyImpulseResponsePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
          'flutter_recorder_aec_applyImpulseResponse');
  late final _flutter_recorder_aec_applyImpulseResponse =
      _flutter_recorder_aec_applyImpulseResponsePtr
          .asFunction<void Function()>();

  /// Get captured calibration signals for visualization
  int flutter_recorder_aec_getCalibrationRefSignal(
    ffi.Pointer<ffi.Float> dest,
    int maxLength,
  ) {
    return _flutter_recorder_aec_getCalibrationRefSignal(
      dest,
      maxLength,
    );
  }

  late final _flutter_recorder_aec_getCalibrationRefSignalPtr = _lookup<
          ffi
          .NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Float>, ffi.Int)>>(
      'flutter_recorder_aec_getCalibrationRefSignal');
  late final _flutter_recorder_aec_getCalibrationRefSignal =
      _flutter_recorder_aec_getCalibrationRefSignalPtr
          .asFunction<int Function(ffi.Pointer<ffi.Float>, int)>();

  int flutter_recorder_aec_getCalibrationMicSignal(
    ffi.Pointer<ffi.Float> dest,
    int maxLength,
  ) {
    return _flutter_recorder_aec_getCalibrationMicSignal(
      dest,
      maxLength,
    );
  }

  late final _flutter_recorder_aec_getCalibrationMicSignalPtr = _lookup<
          ffi
          .NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Float>, ffi.Int)>>(
      'flutter_recorder_aec_getCalibrationMicSignal');
  late final _flutter_recorder_aec_getCalibrationMicSignal =
      _flutter_recorder_aec_getCalibrationMicSignalPtr
          .asFunction<int Function(ffi.Pointer<ffi.Float>, int)>();

  /// Set AEC delay from calibration result
  void flutter_recorder_aec_setDelay(
    double delayMs,
  ) {
    return _flutter_recorder_aec_setDelay(
      delayMs,
    );
  }

  late final _flutter_recorder_aec_setDelayPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
          'flutter_recorder_aec_setDelay');
  late final _flutter_recorder_aec_setDelay =
      _flutter_recorder_aec_setDelayPtr.asFunction<void Function(double)>();

  /// Apply full calibration result: delay + impulse response
  void flutter_recorder_aec_applyCalibration(
    double delayMs,
  ) {
    return _flutter_recorder_aec_applyCalibration(
      delayMs,
    );
  }

  late final _flutter_recorder_aec_applyCalibrationPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
          'flutter_recorder_aec_applyCalibration');
  late final _flutter_recorder_aec_applyCalibration =
      _flutter_recorder_aec_applyCalibrationPtr
          .asFunction<void Function(double)>();

  /// Start capturing test data (raw mic + cancelled output)
  void flutter_recorder_aec_startTestCapture(
    int maxSamples,
  ) {
    return _flutter_recorder_aec_startTestCapture(
      maxSamples,
    );
  }

  late final _flutter_recorder_aec_startTestCapturePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Size)>>(
          'flutter_recorder_aec_startTestCapture');
  late final _flutter_recorder_aec_startTestCapture =
      _flutter_recorder_aec_startTestCapturePtr
          .asFunction<void Function(int)>();

  /// Get calibration log buffer (returns pointer to internal string, do not free)
  ffi.Pointer<ffi.Char> flutter_recorder_aec_getCalibrationLog() {
    return _flutter_recorder_aec_getCalibrationLog();
  }

  late final _flutter_recorder_aec_getCalibrationLogPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'flutter_recorder_aec_getCalibrationLog');
  late final _flutter_recorder_aec_getCalibrationLog =
      _flutter_recorder_aec_getCalibrationLogPtr
          .asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// Clear calibration log buffer
  void flutter_recorder_aec_clearCalibrationLog() {
    return _flutter_recorder_aec_clearCalibrationLog();
  }

  late final _flutter_recorder_aec_clearCalibrationLogPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
          'flutter_recorder_aec_clearCalibrationLog');
  late final _flutter_recorder_aec_clearCalibrationLog =
      _flutter_recorder_aec_clearCalibrationLogPtr
          .asFunction<void Function()>();

  /// Stop capturing test data
  void flutter_recorder_aec_stopTestCapture() {
    return _flutter_recorder_aec_stopTestCapture();
  }

  late final _flutter_recorder_aec_stopTestCapturePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
          'flutter_recorder_aec_stopTestCapture');
  late final _flutter_recorder_aec_stopTestCapture =
      _flutter_recorder_aec_stopTestCapturePtr.asFunction<void Function()>();

  /// Run test analysis and return metrics
  int flutter_recorder_aec_runTest(
    int sampleRate,
    ffi.Pointer<ffi.Float> outCancellationDb,
    ffi.Pointer<ffi.Float> outCorrelationBefore,
    ffi.Pointer<ffi.Float> outCorrelationAfter,
    ffi.Pointer<ffi.Int> outPassed,
    ffi.Pointer<ffi.Float> outMicEnergyDb,
    ffi.Pointer<ffi.Float> outCancelledEnergyDb,
  ) {
    return _flutter_recorder_aec_runTest(
      sampleRate,
      outCancellationDb,
      outCorrelationBefore,
      outCorrelationAfter,
      outPassed,
      outMicEnergyDb,
      outCancelledEnergyDb,
    );
  }

  late final _flutter_recorder_aec_runTestPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.UnsignedInt,
              ffi.Pointer<ffi.Float>,
              ffi.Pointer<ffi.Float>,
              ffi.Pointer<ffi.Float>,
              ffi.Pointer<ffi.Int>,
              ffi.Pointer<ffi.Float>,
              ffi.Pointer<ffi.Float>)>>('flutter_recorder_aec_runTest');
  late final _flutter_recorder_aec_runTest =
      _flutter_recorder_aec_runTestPtr.asFunction<
          int Function(
              int,
              ffi.Pointer<ffi.Float>,
              ffi.Pointer<ffi.Float>,
              ffi.Pointer<ffi.Float>,
              ffi.Pointer<ffi.Int>,
              ffi.Pointer<ffi.Float>,
              ffi.Pointer<ffi.Float>)>();

  /// Get captured test signals for visualization
  int flutter_recorder_aec_getTestMicSignal(
    ffi.Pointer<ffi.Float> dest,
    int maxLength,
  ) {
    return _flutter_recorder_aec_getTestMicSignal(
      dest,
      maxLength,
    );
  }

  late final _flutter_recorder_aec_getTestMicSignalPtr = _lookup<
          ffi
          .NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Float>, ffi.Int)>>(
      'flutter_recorder_aec_getTestMicSignal');
  late final _flutter_recorder_aec_getTestMicSignal =
      _flutter_recorder_aec_getTestMicSignalPtr
          .asFunction<int Function(ffi.Pointer<ffi.Float>, int)>();

  int flutter_recorder_aec_getTestCancelledSignal(
    ffi.Pointer<ffi.Float> dest,
    int maxLength,
  ) {
    return _flutter_recorder_aec_getTestCancelledSignal(
      dest,
      maxLength,
    );
  }

  late final _flutter_recorder_aec_getTestCancelledSignalPtr = _lookup<
          ffi
          .NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Float>, ffi.Int)>>(
      'flutter_recorder_aec_getTestCancelledSignal');
  late final _flutter_recorder_aec_getTestCancelledSignal =
      _flutter_recorder_aec_getTestCancelledSignalPtr
          .asFunction<int Function(ffi.Pointer<ffi.Float>, int)>();

  /// Reset test data
  void flutter_recorder_aec_resetTest() {
    return _flutter_recorder_aec_resetTest();
  }

  late final _flutter_recorder_aec_resetTestPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
          'flutter_recorder_aec_resetTest');
  late final _flutter_recorder_aec_resetTest =
      _flutter_recorder_aec_resetTestPtr.asFunction<void Function()>();

  /// VSS-NLMS parameter control for experimentation
  /// mu_max: Maximum step size (0.0-1.0). Set to 0 to freeze weights.
  void flutter_recorder_aec_setVssMuMax(
    double mu,
  ) {
    return _flutter_recorder_aec_setVssMuMax(
      mu,
    );
  }

  late final _flutter_recorder_aec_setVssMuMaxPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
          'flutter_recorder_aec_setVssMuMax');
  late final _flutter_recorder_aec_setVssMuMax =
      _flutter_recorder_aec_setVssMuMaxPtr.asFunction<void Function(double)>();

  /// leakage: Weight decay factor (0.99-1.0). Set to 1.0 for no decay.
  void flutter_recorder_aec_setVssLeakage(
    double lambda,
  ) {
    return _flutter_recorder_aec_setVssLeakage(
      lambda,
    );
  }

  late final _flutter_recorder_aec_setVssLeakagePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
          'flutter_recorder_aec_setVssLeakage');
  late final _flutter_recorder_aec_setVssLeakage =
      _flutter_recorder_aec_setVssLeakagePtr
          .asFunction<void Function(double)>();

  /// alpha: Smoothing factor for VSS statistics (0.9-0.999).
  void flutter_recorder_aec_setVssAlpha(
    double alpha,
  ) {
    return _flutter_recorder_aec_setVssAlpha(
      alpha,
    );
  }

  late final _flutter_recorder_aec_setVssAlphaPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>(
          'flutter_recorder_aec_setVssAlpha');
  late final _flutter_recorder_aec_setVssAlpha =
      _flutter_recorder_aec_setVssAlphaPtr.asFunction<void Function(double)>();

  /// Getters for current values
  double flutter_recorder_aec_getVssMuMax() {
    return _flutter_recorder_aec_getVssMuMax();
  }

  late final _flutter_recorder_aec_getVssMuMaxPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function()>>(
          'flutter_recorder_aec_getVssMuMax');
  late final _flutter_recorder_aec_getVssMuMax =
      _flutter_recorder_aec_getVssMuMaxPtr.asFunction<double Function()>();

  double flutter_recorder_aec_getVssLeakage() {
    return _flutter_recorder_aec_getVssLeakage();
  }

  late final _flutter_recorder_aec_getVssLeakagePtr =
      _lookup<ffi.NativeFunction<ffi.Float Function()>>(
          'flutter_recorder_aec_getVssLeakage');
  late final _flutter_recorder_aec_getVssLeakage =
      _flutter_recorder_aec_getVssLeakagePtr.asFunction<double Function()>();

  double flutter_recorder_aec_getVssAlpha() {
    return _flutter_recorder_aec_getVssAlpha();
  }

  late final _flutter_recorder_aec_getVssAlphaPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function()>>(
          'flutter_recorder_aec_getVssAlpha');
  late final _flutter_recorder_aec_getVssAlpha =
      _flutter_recorder_aec_getVssAlphaPtr.asFunction<double Function()>();

  /// Filter length control (2048, 4096, 8192 recommended)
  void flutter_recorder_aec_setFilterLength(
    int length,
  ) {
    return _flutter_recorder_aec_setFilterLength(
      length,
    );
  }

  late final _flutter_recorder_aec_setFilterLengthPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>(
          'flutter_recorder_aec_setFilterLength');
  late final _flutter_recorder_aec_setFilterLength =
      _flutter_recorder_aec_setFilterLengthPtr.asFunction<void Function(int)>();

  int flutter_recorder_aec_getFilterLength() {
    return _flutter_recorder_aec_getFilterLength();
  }

  late final _flutter_recorder_aec_getFilterLengthPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>(
          'flutter_recorder_aec_getFilterLength');
  late final _flutter_recorder_aec_getFilterLength =
      _flutter_recorder_aec_getFilterLengthPtr.asFunction<int Function()>();

  /// Position-based sync for sample-accurate AEC
  /// Get total frames written to reference buffer (output side)
  int flutter_recorder_aec_getOutputFrameCount() {
    return _flutter_recorder_aec_getOutputFrameCount();
  }

  late final _flutter_recorder_aec_getOutputFrameCountPtr =
      _lookup<ffi.NativeFunction<ffi.Size Function()>>(
          'flutter_recorder_aec_getOutputFrameCount');
  late final _flutter_recorder_aec_getOutputFrameCount =
      _flutter_recorder_aec_getOutputFrameCountPtr.asFunction<int Function()>();

  /// Get total frames captured by recorder (input side)
  int flutter_recorder_aec_getCaptureFrameCount() {
    return _flutter_recorder_aec_getCaptureFrameCount();
  }

  late final _flutter_recorder_aec_getCaptureFrameCountPtr =
      _lookup<ffi.NativeFunction<ffi.Size Function()>>(
          'flutter_recorder_aec_getCaptureFrameCount');
  late final _flutter_recorder_aec_getCaptureFrameCount =
      _flutter_recorder_aec_getCaptureFrameCountPtr
          .asFunction<int Function()>();

  /// Record frame counters at calibration start
  void flutter_recorder_aec_recordCalibrationFrameCounters() {
    return _flutter_recorder_aec_recordCalibrationFrameCounters();
  }

  late final _flutter_recorder_aec_recordCalibrationFrameCountersPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
          'flutter_recorder_aec_recordCalibrationFrameCounters');
  late final _flutter_recorder_aec_recordCalibrationFrameCounters =
      _flutter_recorder_aec_recordCalibrationFrameCountersPtr
          .asFunction<void Function()>();

  /// Set calibrated offset: captureFrame - offset = outputFrame
  void flutter_recorder_aec_setCalibratedOffset(
    int offset,
  ) {
    return _flutter_recorder_aec_setCalibratedOffset(
      offset,
    );
  }

  late final _flutter_recorder_aec_setCalibratedOffsetPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'flutter_recorder_aec_setCalibratedOffset');
  late final _flutter_recorder_aec_setCalibratedOffset =
      _flutter_recorder_aec_setCalibratedOffsetPtr
          .asFunction<void Function(int)>();

  /// Get current calibrated offset
  int flutter_recorder_aec_getCalibratedOffset() {
    return _flutter_recorder_aec_getCalibratedOffset();
  }

  late final _flutter_recorder_aec_getCalibratedOffsetPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
          'flutter_recorder_aec_getCalibratedOffset');
  late final _flutter_recorder_aec_getCalibratedOffset =
      _flutter_recorder_aec_getCalibratedOffsetPtr.asFunction<int Function()>();

  /// //////////////////////
  /// iOS Hardware Control
  /// //////////////////////
  void flutter_recorder_ios_force_speaker_output(
    bool enabled,
  ) {
    return _flutter_recorder_ios_force_speaker_output(
      enabled,
    );
  }

  late final _flutter_recorder_ios_force_speaker_outputPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
          'flutter_recorder_ios_force_speaker_output');
  late final _flutter_recorder_ios_force_speaker_output =
      _flutter_recorder_ios_force_speaker_outputPtr
          .asFunction<void Function(bool)>();

  /// //////////////////////
  /// Aligned Calibration Capture (frame-aligned signals from processAudio)
  /// //////////////////////
  void flutter_recorder_aec_startAlignedCalibrationCapture(
    int maxSamples,
  ) {
    return _flutter_recorder_aec_startAlignedCalibrationCapture(
      maxSamples,
    );
  }

  late final _flutter_recorder_aec_startAlignedCalibrationCapturePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Size)>>(
          'flutter_recorder_aec_startAlignedCalibrationCapture');
  late final _flutter_recorder_aec_startAlignedCalibrationCapture =
      _flutter_recorder_aec_startAlignedCalibrationCapturePtr
          .asFunction<void Function(int)>();

  void flutter_recorder_aec_stopAlignedCalibrationCapture() {
    return _flutter_recorder_aec_stopAlignedCalibrationCapture();
  }

  late final _flutter_recorder_aec_stopAlignedCalibrationCapturePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
          'flutter_recorder_aec_stopAlignedCalibrationCapture');
  late final _flutter_recorder_aec_stopAlignedCalibrationCapture =
      _flutter_recorder_aec_stopAlignedCalibrationCapturePtr
          .asFunction<void Function()>();

  int flutter_recorder_aec_runAlignedCalibrationWithImpulse(
    int sampleRate,
    ffi.Pointer<ffi.Int> outDelaySamples,
    ffi.Pointer<ffi.Float> outDelayMs,
    ffi.Pointer<ffi.Float> outGain,
    ffi.Pointer<ffi.Float> outCorrelation,
    ffi.Pointer<ffi.Int> outImpulseLength,
    ffi.Pointer<ffi.Int64> outCalibratedOffset,
    int signalType,
  ) {
    return _flutter_recorder_aec_runAlignedCalibrationWithImpulse(
      sampleRate,
      outDelaySamples,
      outDelayMs,
      outGain,
      outCorrelation,
      outImpulseLength,
      outCalibratedOffset,
      signalType,
    );
  }

  late final _flutter_recorder_aec_runAlignedCalibrationWithImpulsePtr =
      _lookup<
              ffi.NativeFunction<
                  ffi.Int Function(
                      ffi.UnsignedInt,
                      ffi.Pointer<ffi.Int>,
                      ffi.Pointer<ffi.Float>,
                      ffi.Pointer<ffi.Float>,
                      ffi.Pointer<ffi.Float>,
                      ffi.Pointer<ffi.Int>,
                      ffi.Pointer<ffi.Int64>,
                      ffi.Int)>>(
          'flutter_recorder_aec_runAlignedCalibrationWithImpulse');
  late final _flutter_recorder_aec_runAlignedCalibrationWithImpulse =
      _flutter_recorder_aec_runAlignedCalibrationWithImpulsePtr.asFunction<
          int Function(
              int,
              ffi.Pointer<ffi.Int>,
              ffi.Pointer<ffi.Float>,
              ffi.Pointer<ffi.Float>,
              ffi.Pointer<ffi.Float>,
              ffi.Pointer<ffi.Int>,
              ffi.Pointer<ffi.Int64>,
              int)>();
}

typedef dartSilenceChangedCallback_t
    = ffi.Pointer<ffi.NativeFunction<dartSilenceChangedCallback_tFunction>>;
typedef dartSilenceChangedCallback_tFunction = ffi.Void Function(
    ffi.Pointer<ffi.Bool>, ffi.Pointer<ffi.Float>);
typedef DartdartSilenceChangedCallback_tFunction = void Function(
    ffi.Pointer<ffi.Bool>, ffi.Pointer<ffi.Float>);
typedef dartStreamDataCallback_t
    = ffi.Pointer<ffi.NativeFunction<dartStreamDataCallback_tFunction>>;
typedef dartStreamDataCallback_tFunction = ffi.Void Function(
    ffi.Pointer<ffi.UnsignedChar> data, ffi.Int dataLength);
typedef DartdartStreamDataCallback_tFunction = void Function(
    ffi.Pointer<ffi.UnsignedChar> data, int dataLength);

/// Possible capture errors
enum CaptureErrors {
  /// No error
  captureNoError(0),

  /// The capture device has failed to initialize.
  captureInitFailed(1),

  /// The capture device has not yet been initialized.
  captureNotInited(2),

  /// Failed to start the device.
  failedToStartDevice(3),

  /// Failed to initialize wav recording.
  failedToInitializeRecording(4),

  /// Invalid arguments while initializing wav recording.
  invalidArgs(5),

  /// Failed to write wav file.
  failedToWriteWav(6),

  /// Filter not found
  filterNotFound(7),

  /// The filter has already been added.
  filterAlreadyAdded(8),

  /// Error getting filter parameter.
  filterParameterGetError(9);

  final int value;
  const CaptureErrors(this.value);

  static CaptureErrors fromValue(int value) => switch (value) {
        0 => captureNoError,
        1 => captureInitFailed,
        2 => captureNotInited,
        3 => failedToStartDevice,
        4 => failedToInitializeRecording,
        5 => invalidArgs,
        6 => failedToWriteWav,
        7 => filterNotFound,
        8 => filterAlreadyAdded,
        9 => filterParameterGetError,
        _ => throw ArgumentError("Unknown value for CaptureErrors: $value"),
      };
}

enum RecorderFilterType {
  autogain(0),
  echoCancellation(1),
  adaptiveEchoCancellation(2);

  final int value;
  const RecorderFilterType(this.value);

  static RecorderFilterType fromValue(int value) => switch (value) {
        0 => autogain,
        1 => echoCancellation,
        2 => adaptiveEchoCancellation,
        _ =>
          throw ArgumentError("Unknown value for RecorderFilterType: $value"),
      };
}

/// Run calibration analysis with impulse response computation
/// AecStats defined in enums.h
typedef AecStatsCallback
    = ffi.Pointer<ffi.NativeFunction<AecStatsCallbackFunction>>;
typedef AecStatsCallbackFunction = ffi.Void Function(AecStats stats);
typedef DartAecStatsCallbackFunction = void Function(AecStats stats);

final class AecStats extends ffi.Struct {
  @ffi.Float()
  external double maxAttenuationDb;

  @ffi.Float()
  external double correlation;

  @ffi.Float()
  external double echoReturnLossDb;

  /// Current filter length in samples
  @ffi.Int()
  external int filterLength;

  /// Configured max step size
  @ffi.Float()
  external double muMax;

  /// Last effective step size (runtime)
  @ffi.Float()
  external double muEffective;

  /// Last error in dB
  @ffi.Float()
  external double lastErrorDb;

  /// Instantaneous correlation metric
  @ffi.Float()
  external double instantCorrelation;
}
